# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheManWhoLaughs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50, null=True)),
                ('song', models.CharField(max_length=400, null=True)),
                ('music', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
