# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheManWhoLaughs',
            new_name='TheManWhoLaugh',
        ),
    ]
