# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0004_auto_20180525_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMWL_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
