# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0005_tmwl_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMWL_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
