# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0006_tmwl_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TMWL_english',
            new_name='chinese',
        ),
        migrations.RenameModel(
            old_name='TMWL_chinese',
            new_name='english',
        ),
        migrations.RenameModel(
            old_name='TMWL_japanese',
            new_name='japanese',
        ),
        migrations.RenameModel(
            old_name='TMWL_korean',
            new_name='korean',
        ),
    ]
