# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0007_auto_20180608_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinese',
            name='musical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='musical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='japanese',
            name='musical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='korean',
            name='musical',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
